W-y :enter timeout=1000 abort=auto
W-y y :exec dmenu_docs papers
W-y t :exec dmenu_docs books
W-y u :exec dmenu_docs documents
W-y r :exec dmenu_clipmenu
W-y s :exec dmenu_screens
W-colon :enter timeout=1000 abort=auto
W-colon colon :exec demoronize
W-colon l :exec notifications_off
W-colon S-l :exec notifications_on
W-C-space :exec dunstctl close
W-C-S-space :exec dunstctl close-all
W-C-grave :exec dunstctl history-pop
W-C-S-period :exec dunstctl context
XF86AudioLowerVolume :exec pactl set-sink-volume @DEFAULT_SINK@ -5%
XF86AudioRaiseVolume :exec pactl set-sink-volume @DEFAULT_SINK@ +5%
XF86AudioMute :exec pactl set-sink-mut @DEFAULT_SINK@ toggle
W-C-XF86Eject :exec slock
W-C-F12 :exec slock
W-Up :exec pactl set-sink-volume @DEFAULT_SINK@ +5%
W-Down :exec pactl set-sink-volume @DEFAULT_SINK@ -5%
W-Delete :exec pactl set-sink-mute @DEFAULT_SINK@ toggle
W-F5 :exec xbacklight -dec 2
W-F6 :exec xbacklight -inc 2
# W-C-v :exec sh -c 'xsel | xvkbd -xsendevent -file - 2>/dev/null'
